# Generated by Django 5.0.2 on 2025-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("note", "Note"),
                            ("review", "Review"),
                            ("file_text", "File Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("owner_id", models.CharField(max_length=255)),
                ("vector", models.BinaryField()),
                ("model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_type", "owner_id"],
                        name="search_sear_owner_t_a0acd5_idx",
                    ),
                    models.Index(fields=["model"], name="search_sear_model_9f44ee_idx"),
                ],
                "unique_together": {("owner_type", "owner_id", "model")},
            },
        ),
    ]
