# Generated by Django 5.0.2 on 2025-08-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Libraries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LibraryBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("custom_notes_summary", models.TextField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_books",
                        to="books.book",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_books",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="LibraryBookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.librarybook",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.tag"
                    ),
                ),
            ],
            options={
                "unique_together": {("library_book", "tag")},
            },
        ),
        migrations.AddField(
            model_name="librarybook",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="libraries.LibraryBookTag", to="books.tag"
            ),
        ),
        migrations.CreateModel(
            name="ShelfItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libraries.librarybook",
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.shelf"
                    ),
                ),
            ],
            options={
                "unique_together": {("shelf", "library_book")},
            },
        ),
        migrations.AddField(
            model_name="librarybook",
            name="shelves",
            field=models.ManyToManyField(
                blank=True, through="libraries.ShelfItem", to="books.shelf"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="librarybook",
            unique_together={("library", "book")},
        ),
    ]
