# Generated by Django 5.0.2 on 2025-08-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="System libraries cannot be deleted"
            ),
        ),
    ]
