# Generated by Django 5.0.2 on 2025-08-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_bookcoverimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("number", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "number", "title"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="books.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SubSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="books.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="PageRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_ranges",
                        to="books.chapter",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_ranges",
                        to="books.section",
                    ),
                ),
                (
                    "subsection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_ranges",
                        to="books.subsection",
                    ),
                ),
            ],
            options={
                "ordering": ["start_page"],
            },
        ),
        migrations.DeleteModel(
            name="BookCoverImage",
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["book", "order"], name="books_chapt_book_id_5eb607_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["book", "number"], name="books_chapt_book_id_f7833d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("book", "order")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["chapter", "order"], name="books_secti_chapter_884890_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("chapter", "order")},
        ),
        migrations.AddIndex(
            model_name="subsection",
            index=models.Index(
                fields=["section", "order"], name="books_subse_section_780fa5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subsection",
            unique_together={("section", "order")},
        ),
        migrations.AddIndex(
            model_name="pagerange",
            index=models.Index(
                fields=["start_page", "end_page"], name="books_pager_start_p_4b2a57_idx"
            ),
        ),
    ]
