# Generated by Django 5.0.2 on 2025-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0002_library_is_system"),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rating",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category for the rating (e.g., 'overall', 'plot', 'characters')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("library_book", "category")},
        ),
    ]
