# Generated by Django 5.0.2 on 2025-08-28 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_chapter_section_subsection_pagerange_and_more"),
        ("libraries", "0002_library_is_system"),
        ("notes", "0002_alter_rating_unique_together_rating_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("excalidraw_data", models.JSONField()),
                ("preview_png", models.BinaryField(blank=True, null=True)),
                ("preview_svg", models.TextField(blank=True)),
                ("width", models.PositiveIntegerField(default=800)),
                ("height", models.PositiveIntegerField(default=600)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteDiagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="note",
            name="content_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="content_blocks_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="note",
            name="ref_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_notes",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="ref_chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_notes",
                to="books.chapter",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="ref_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_notes",
                to="books.section",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="ref_subsection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referenced_notes",
                to="books.subsection",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["ref_book"], name="notes_note_ref_boo_f3b02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["ref_chapter"], name="notes_note_ref_cha_a03b3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["ref_section"], name="notes_note_ref_sec_4185f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["ref_subsection"], name="notes_note_ref_sub_3e2c7b_idx"
            ),
        ),
        migrations.AddField(
            model_name="notediagram",
            name="diagram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_diagrams",
                to="notes.diagram",
            ),
        ),
        migrations.AddField(
            model_name="notediagram",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_diagrams",
                to="notes.note",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notediagram",
            unique_together={("note", "diagram")},
        ),
    ]
