# Generated by Django 5.0.2 on 2025-08-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("epub", "EPUB")], max_length=10
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("object_key", models.CharField(blank=True, max_length=500, null=True)),
                ("bytes", models.BigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("text_extracted", models.BooleanField(default=False)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                (
                    "library_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="libraries.librarybook",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
